name: Backend Pipeline CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies (Pipeline Service)
      run: |
        cd project-root/pipeline_service
        pip install -r requirements.txt

    - name: Install Dependencies (Mock Server)
      run: |
        cd project-root/mock_server
        pip install -r requirements.txt

    - name: Python Syntax Check
      run: |
        python -m py_compile $(git ls-files '*.py')

    - name: Build Docker
      run: |
        cd project-root
        docker compose build